[20] Failed to execute script irankfinder
Traceback (most recent call last):
  File "irankfinder.py", line 374, in <module>
  File "irankfinder.py", line 223, in launch
  File "irankfinder.py", line 251, in analyse
  File "termination/__init__.py", line 81, in analyse
  File "partialevaluation/__init__.py", line 61, in control_flow_refinement
  File "partialevaluation/__init__.py", line 109, in partialevaluate
Exception: b"mkdir: cannot create directory '/tmp/tmp0sloovmh': Operation not permitted\nError when creating /tmp/tmp0sloovmh/source_81a88e_output folder\n"
